/* One on-demand renderer. Reuses loaded geometry; draws only while the garage is visible. */
(()=>{
 const host=document.getElementById('driver-preview-canvas'),panel=document.getElementById('settings-panel'),pane=document.getElementById('pane-garage');if(!host)return;
 const status=document.getElementById('driver-preview-status'),T=THREE;
 let renderer,scene,camera,model,owned=[],geometries=[],textures=[],frame=0,last=0,yaw=.65,pitch=.24,zoom=.72,drag=null,auto=true,key=null,loading=false,environment;
 let inView=false;const visible=()=>panel.open&&!pane.hidden&&!document.hidden&&inView;
 function disposeModel(){if(model)scene.remove(model);for(const m of owned)m.dispose();for(const g of geometries)g.dispose();for(const t of textures)t.dispose();model=null;owned=[];geometries=[];textures=[];}
 function init(){if(renderer)return;renderer=new T.WebGLRenderer({antialias:true,alpha:false});renderer.setPixelRatio(Math.min(devicePixelRatio,1.25));renderer.outputColorSpace=T.SRGBColorSpace;renderer.toneMapping=T.ACESFilmicToneMapping;renderer.toneMappingExposure=1.3;renderer.domElement.setAttribute('aria-label','Modelo tridimensional do motorista');renderer.domElement.style.touchAction='pan-y';host.append(renderer.domElement);scene=new T.Scene();scene.background=new T.Color('#152a29');camera=new T.PerspectiveCamera(42,1,.05,100);
  scene.add(new T.HemisphereLight('#e8f5f2','#4c625d',3));for(const [x,y,z,intensity] of [[4,6,5,4],[-4,3,-4,2]]){const light=new T.DirectionalLight('#ffffff',intensity);light.position.set(x,y,z);scene.add(light);}
  const studio=new T.Scene();studio.background=new T.Color('#9eb6b1');const emit=new T.MeshBasicMaterial({color:'#ffffff'}),geometry=new T.BoxGeometry(1,1,1);for(const [x,y,z,sx,sy,sz] of [[0,5,0,8,.1,8],[-5,2,0,.1,4,8],[4,3,3,.1,3,4]]){const box=new T.Mesh(geometry,emit);box.position.set(x,y,z);box.scale.set(sx,sy,sz);studio.add(box);}const generator=new T.PMREMGenerator(renderer);environment=generator.fromScene(studio,.08);scene.environment=environment.texture;generator.dispose();geometry.dispose();emit.dispose();
  const floor=new T.Mesh(new T.CircleGeometry(1.5,48),new T.MeshStandardMaterial({color:'#203b38',roughness:.9}));floor.rotation.x=-Math.PI/2;floor.position.y=-.025;scene.add(floor);const shadow=new T.Mesh(new T.CircleGeometry(.45,32),new T.MeshBasicMaterial({color:'#081917',transparent:true,opacity:.42,depthWrite:false}));shadow.rotation.x=-Math.PI/2;shadow.position.y=-.018;scene.add(shadow);
  renderer.domElement.addEventListener('pointerdown',e=>{if(e.pointerType==='touch')renderer.domElement.style.touchAction='none';renderer.domElement.setPointerCapture(e.pointerId);drag={x:e.clientX,y:e.clientY};auto=false;});renderer.domElement.addEventListener('pointermove',e=>{if(!drag)return;yaw-=(e.clientX-drag.x)*.009;pitch=Math.max(.08,Math.min(.85,pitch+(e.clientY-drag.y)*.005));drag={x:e.clientX,y:e.clientY};});const release=()=>{drag=null;renderer.domElement.style.touchAction='pan-y';};renderer.domElement.addEventListener('pointerup',release);renderer.domElement.addEventListener('pointercancel',release);renderer.domElement.addEventListener('wheel',e=>{e.preventDefault();zoom=Math.max(.62,Math.min(1.7,zoom*Math.exp(e.deltaY*.001)));auto=false;},{passive:false});new ResizeObserver(resize).observe(host);
 }
 function resize(){if(!renderer||!host.clientWidth)return;const width=host.clientWidth,height=host.clientHeight;renderer.setSize(width,height,false);camera.aspect=width/height;camera.updateProjectionMatrix();}
 let version=0;
 async function refresh(){if(!visible())return;init();const selected=HorizonSettings.config.driverModel,profile=HorizonDrivers[selected],token=++version;status.textContent='Carregando motorista…';key=selected;
 try{let gltf;if(profile.procedural){const holder=new T.Group(),lever=new T.Group();holder.add(lever);const driver=new Driver(holder,{x:0,y:.75,z:.64,radius:.17},lever);await driver.ready;driver.setCameraMode(0);gltf={scene:holder};}else{if(!window[profile.asset])await new Promise((resolve,reject)=>{const script=document.createElement('script');script.src=profile.script;script.onload=resolve;script.onerror=reject;document.head.append(script);});const bytes=Uint8Array.from(atob(window[profile.asset]),c=>c.charCodeAt(0));gltf=await new Promise((resolve,reject)=>new T.GLTFLoader().parse(bytes.buffer,'',resolve,reject));}if(token!==version)return;disposeModel();model=gltf.scene;scene.add(model);owned=[];model.traverse(o=>{if(o.isMesh){geometries.push(o.geometry);[].concat(o.material).forEach(m=>{owned.push(m);for(const value of Object.values(m))if(value?.isTexture)textures.push(value);});}});model.updateMatrixWorld(true);const box=new T.Box3().setFromObject(model),size=box.getSize(new T.Vector3()),factor=1.8/size.y;model.scale.multiplyScalar(factor);model.updateMatrixWorld(true);const fitted=new T.Box3().setFromObject(model);model.position.y-=fitted.min.y;model.updateMatrixWorld(true);const finalBox=new T.Box3().setFromObject(model);model.userData.previewCenter=finalBox.getCenter(new T.Vector3());model.userData.previewRadius=finalBox.getSize(new T.Vector3()).length()/2;yaw=.4;pitch=.1;zoom=1;auto=true;status.textContent=profile.name;resize();}catch(error){status.textContent='Não foi possível carregar a prévia.';console.error(error);}}
 function render(time){frame=0;if(!visible()){last=0;return;}if(time-last>=1000/30){const dt=last?Math.min(.1,(time-last)/1000):0;last=time;if(auto)yaw+=dt*.14;if(model){const center=model.userData.previewCenter,radius=model.userData.previewRadius,angle=Math.min(camera.fov*Math.PI/360,Math.atan(Math.tan(camera.fov*Math.PI/360)*camera.aspect)),distance=radius/Math.sin(angle)*1.08*zoom;camera.position.set(center.x+Math.sin(yaw)*Math.cos(pitch)*distance,center.y+Math.sin(pitch)*distance,center.z+Math.cos(yaw)*Math.cos(pitch)*distance);camera.lookAt(center);}renderer.render(scene,camera);}frame=requestAnimationFrame(render);}
 function sync(){if(visible()){init();if(key!==HorizonSettings.config.driverModel)refresh();resize();if(!frame)frame=requestAnimationFrame(render);}else if(frame){cancelAnimationFrame(frame);frame=0;last=0;}}
 document.getElementById('driver-preview-reset').onclick=()=>{yaw=.4;pitch=.1;zoom=1;auto=true;};
 window.addEventListener('horizon-driver-loading',()=>{loading=true;if(visible()){status.textContent='Carregando prévia 3D…';if(renderer)disposeModel();}});
 window.addEventListener('horizon-driver-ready',()=>{loading=false;sync();});
 window.addEventListener('horizon-settings',e=>{if(e.detail.key==='driverModel'||e.detail.key==='all'){key=null;refresh();sync();}});
 new IntersectionObserver(entries=>{inView=entries[0].isIntersecting;sync();},{threshold:.01}).observe(host);
 new MutationObserver(sync).observe(panel,{attributes:true,attributeFilter:['open'],subtree:false});new MutationObserver(sync).observe(pane,{attributes:true,attributeFilter:['hidden']});document.addEventListener('visibilitychange',sync);
})();
