/* One on-demand renderer. Reuses loaded geometry; draws only while the garage is visible. */
(()=>{
 const host=document.getElementById('garage-preview-canvas'),panel=document.getElementById('settings-panel'),pane=document.getElementById('pane-garage');if(!host)return;
 const status=document.getElementById('garage-preview-status'),T=THREE;
 let renderer,scene,camera,model,owned=[],frame=0,last=0,yaw=.65,pitch=.24,zoom=.72,drag=null,auto=true,key=null,loading=false,environment;
 const visible=()=>panel.open&&!pane.hidden&&!document.hidden;
 function disposeModel(){if(model)scene.remove(model);for(const m of owned)m.dispose();model=null;owned=[];}
 function init(){if(renderer)return;renderer=new T.WebGLRenderer({antialias:true,alpha:false});renderer.setPixelRatio(Math.min(devicePixelRatio,1.25));renderer.outputColorSpace=T.SRGBColorSpace;renderer.toneMapping=T.ACESFilmicToneMapping;renderer.toneMappingExposure=1.3;renderer.domElement.setAttribute('aria-label','Modelo tridimensional do carro');renderer.domElement.style.touchAction='pan-y';host.append(renderer.domElement);scene=new T.Scene();scene.background=new T.Color('#152a29');camera=new T.PerspectiveCamera(42,1,.05,100);
  scene.add(new T.HemisphereLight('#e8f5f2','#4c625d',3));for(const [x,y,z,intensity] of [[4,6,5,4],[-4,3,-4,2]]){const light=new T.DirectionalLight('#ffffff',intensity);light.position.set(x,y,z);scene.add(light);}
  const studio=new T.Scene();studio.background=new T.Color('#9eb6b1');const emit=new T.MeshBasicMaterial({color:'#ffffff'}),geometry=new T.BoxGeometry(1,1,1);for(const [x,y,z,sx,sy,sz] of [[0,5,0,8,.1,8],[-5,2,0,.1,4,8],[4,3,3,.1,3,4]]){const box=new T.Mesh(geometry,emit);box.position.set(x,y,z);box.scale.set(sx,sy,sz);studio.add(box);}const generator=new T.PMREMGenerator(renderer);environment=generator.fromScene(studio,.08);scene.environment=environment.texture;generator.dispose();geometry.dispose();emit.dispose();
  const floor=new T.Mesh(new T.CircleGeometry(4,64),new T.MeshStandardMaterial({color:'#203b38',roughness:.9}));floor.rotation.x=-Math.PI/2;floor.position.y=-.025;scene.add(floor);const shadow=new T.Mesh(new T.PlaneGeometry(2.1,4.7),new T.MeshBasicMaterial({color:'#081917',transparent:true,opacity:.42,depthWrite:false}));shadow.rotation.x=-Math.PI/2;shadow.position.y=-.018;scene.add(shadow);
  renderer.domElement.addEventListener('pointerdown',e=>{if(e.pointerType==='touch')renderer.domElement.style.touchAction='none';renderer.domElement.setPointerCapture(e.pointerId);drag={x:e.clientX,y:e.clientY};auto=false;});renderer.domElement.addEventListener('pointermove',e=>{if(!drag)return;yaw-=(e.clientX-drag.x)*.009;pitch=Math.max(.08,Math.min(.85,pitch+(e.clientY-drag.y)*.005));drag={x:e.clientX,y:e.clientY};});const release=()=>{drag=null;renderer.domElement.style.touchAction='pan-y';};renderer.domElement.addEventListener('pointerup',release);renderer.domElement.addEventListener('pointercancel',release);renderer.domElement.addEventListener('wheel',e=>{e.preventDefault();zoom=Math.max(.62,Math.min(1.7,zoom*Math.exp(e.deltaY*.001)));auto=false;},{passive:false});new ResizeObserver(resize).observe(host);
 }
 function resize(){if(!renderer||!host.clientWidth)return;const width=host.clientWidth,height=host.clientHeight;renderer.setSize(width,height,false);camera.aspect=width/height;camera.updateProjectionMatrix();}
 function refresh(){if(!visible())return;init();const selected=HorizonSettings.config.carModel;if(loading||!window.Horizon?.vehicle?.ready){status.textContent='Carregando prévia 3D…';return;}const copy=Horizon.vehicle.previewModel();if(!copy)return;disposeModel();model=copy.root;owned=copy.materials;scene.add(model);key=selected;yaw=.65;pitch=.24;zoom=.72;auto=true;model.updateMatrixWorld(true);const box=new T.Box3().setFromObject(model),size=box.getSize(new T.Vector3());model.userData.previewCenter=box.getCenter(new T.Vector3());model.userData.previewRadius=Math.max(size.length()/2,2.5);status.textContent=HorizonCars[key].name;resize();}
 function render(time){frame=0;if(!visible()){last=0;return;}if(time-last>=1000/30){const dt=last?Math.min(.1,(time-last)/1000):0;last=time;if(auto)yaw+=dt*.14;if(model){const center=model.userData.previewCenter,radius=model.userData.previewRadius,angle=Math.min(camera.fov*Math.PI/360,Math.atan(Math.tan(camera.fov*Math.PI/360)*camera.aspect)),distance=radius/Math.sin(angle)*1.08*zoom;camera.position.set(center.x+Math.sin(yaw)*Math.cos(pitch)*distance,center.y+Math.sin(pitch)*distance,center.z+Math.cos(yaw)*Math.cos(pitch)*distance);camera.lookAt(center);}renderer.render(scene,camera);}frame=requestAnimationFrame(render);}
 function sync(){if(visible()){init();if(key!==HorizonSettings.config.carModel||!model)refresh();resize();if(!frame)frame=requestAnimationFrame(render);}else if(frame){cancelAnimationFrame(frame);frame=0;last=0;}}
 document.getElementById('garage-preview-reset').onclick=()=>{yaw=.65;pitch=.24;zoom=.72;auto=true;};
 window.addEventListener('horizon-car-loading',()=>{loading=true;if(visible()){status.textContent='Carregando prévia 3D…';if(renderer)disposeModel();}});
 window.addEventListener('horizon-car-ready',()=>{loading=false;key=null;refresh();sync();});
 window.addEventListener('horizon-settings',e=>{if(e.detail.key==='carColor'&&model)for(const m of owned)if(HorizonCars[key]?.paint?.test(m.name||''))m.color.set(HorizonSettings.config.carColor);if(e.detail.key==='driverSide'||e.detail.key==='all'){key=null;requestAnimationFrame(()=>{refresh();sync();});}});
 new MutationObserver(sync).observe(panel,{attributes:true,attributeFilter:['open'],subtree:false});new MutationObserver(sync).observe(pane,{attributes:true,attributeFilter:['hidden']});document.addEventListener('visibilitychange',sync);
})();
